name = "inknoir"
compatibility_date = "2026-06-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[kv_namespaces]]
binding = "SESSION"
id = "67a9413c815747479cb8d394221d90c1"

[[d1_databases]]
binding = "DB"
database_name = "inknoir-catalog"
database_id = "18219077-0bbb-4a1b-8c85-ff088df600d7"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "inknoir-assets"

[vars]
PUBLIC_CHAIN_ID = "97"
PUBLIC_BSC_RPC_PRIMARY = "https://data-seed-prebsc-1-s1.binance.org:8545"
PUBLIC_BSC_RPC_FALLBACK = "https://data-seed-prebsc-2-s1.binance.org:8545"
PUBLIC_CONTRACT_ADDRESS = "PLACEHOLDER_FILLED_BY_DEPLOY"
PUBLIC_USDT_ADDRESS = "0x337610d27c682E347C9cD60BD4b3b107C9d34dDd"
R2_PUBLIC_URL = "https://pub-7749af21c6f240d6b28a5f8b8711d8e3.r2.dev"
PRIVY_APP_ID = "cmq6cb76a00c20dif8ne3ubyx"
PUBLIC_PRIVY_APP_ID = "cmq6cb76a00c20dif8ne3ubyx"
