#!/usr/bin/env bash
set -euo pipefail

# Deploys SuknidPlates to Base Sepolia and writes the address to contract.ts.
# Required env vars: BASE_SEPOLIA_RPC, BASESCAN_API_KEY, SIGNER_ADDRESS, ARTIST_TREASURY

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONTRACTS_DIR="$REPO_ROOT/contracts"
DEPLOY_JSON="$CONTRACTS_DIR/deployments/base-sepolia.json"
CONTRACT_TS="$REPO_ROOT/src/lib/config/contract.ts"

cd "$CONTRACTS_DIR"

echo "Building contracts..."
forge build

echo "Deploying to Base Sepolia..."
forge script script/Deploy.s.sol:DeployScript \
  --rpc-url "$BASE_SEPOLIA_RPC" \
  --broadcast \
  --verify \
  --etherscan-api-key "$BASESCAN_API_KEY" \
  -vvvv

# Extract address from broadcast artifacts.
BROADCAST_FILE="$CONTRACTS_DIR/broadcast/Deploy.s.sol/84532/run-latest.json"
if [ ! -f "$BROADCAST_FILE" ]; then
  echo "ERROR: Broadcast file not found at $BROADCAST_FILE" >&2
  exit 1
fi

ADDRESS=$(jq -r '.transactions[] | select(.transactionType=="CREATE") | .contractAddress' "$BROADCAST_FILE" | head -1)
DEPLOY_BLOCK=$(jq -r '.receipts[0].blockNumber' "$BROADCAST_FILE")
# Convert hex block number to decimal.
DEPLOY_BLOCK_DEC=$(printf '%d' "$DEPLOY_BLOCK")

echo "Deployed SuknidPlates at $ADDRESS (block $DEPLOY_BLOCK_DEC)"

# Write deployment JSON.
mkdir -p "$(dirname "$DEPLOY_JSON")"
cat > "$DEPLOY_JSON" <<JSON
{
  "address": "$ADDRESS",
  "chainId": 84532,
  "deployBlock": $DEPLOY_BLOCK_DEC,
  "abi": [
    {"type":"constructor","inputs":[{"name":"signer","type":"address"},{"name":"treasury","type":"address"}],"stateMutability":"nonpayable"},
    {"type":"function","name":"mintWithVoucher","inputs":[{"name":"voucher","type":"tuple","components":[{"name":"tokenId","type":"uint256"},{"name":"designId","type":"string"},{"name":"price","type":"uint256"},{"name":"artistTreasury","type":"address"},{"name":"expiry","type":"uint256"},{"name":"buyer","type":"address"},{"name":"cidHash","type":"bytes32"}]},{"name":"signature","type":"bytes"},{"name":"cid","type":"string"}],"outputs":[],"stateMutability":"payable"},
    {"type":"function","name":"setAuthorizedSigner","inputs":[{"name":"newSigner","type":"address"}],"outputs":[],"stateMutability":"nonpayable"},
    {"type":"function","name":"tokenURI","inputs":[{"name":"tokenId","type":"uint256"}],"outputs":[{"name":"","type":"string"}],"stateMutability":"view"},
    {"type":"function","name":"authorizedSigner","inputs":[],"outputs":[{"name":"","type":"address"}],"stateMutability":"view"},
    {"type":"function","name":"ownerOf","inputs":[{"name":"tokenId","type":"uint256"}],"outputs":[{"name":"","type":"address"}],"stateMutability":"view"},
    {"type":"function","name":"balanceOf","inputs":[{"name":"owner","type":"address"}],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
    {"type":"event","name":"PlateMinted","inputs":[{"name":"tokenId","type":"uint256","indexed":true},{"name":"buyer","type":"address","indexed":true},{"name":"designId","type":"string","indexed":false}],"anonymous":false},
    {"type":"event","name":"SignerRotated","inputs":[{"name":"oldSigner","type":"address","indexed":true},{"name":"newSigner","type":"address","indexed":true}],"anonymous":false},
    {"type":"event","name":"Transfer","inputs":[{"name":"from","type":"address","indexed":true},{"name":"to","type":"address","indexed":true},{"name":"tokenId","type":"uint256","indexed":true}],"anonymous":false}
  ]
}
JSON

echo "Wrote deployment JSON to $DEPLOY_JSON"

# Write / update src/lib/config/contract.ts.
mkdir -p "$(dirname "$CONTRACT_TS")"
cat > "$CONTRACT_TS" <<TS
// Auto-generated by scripts/deploy-contract.sh — do not edit manually.
// Run \`bash scripts/deploy-contract.sh\` after deploying to Base Sepolia.
import type { Abi } from "viem";

export const CONTRACT_ADDRESS = "$ADDRESS" as \`0x\${string}\`;
export const CHAIN_ID = 84532 as const;
export const DEPLOY_BLOCK = BigInt($DEPLOY_BLOCK_DEC);

export const CONTRACT_ABI = [
  {
    type: "function",
    name: "mintWithVoucher",
    inputs: [
      {
        name: "voucher",
        type: "tuple",
        components: [
          { name: "tokenId", type: "uint256" },
          { name: "designId", type: "string" },
          { name: "price", type: "uint256" },
          { name: "artistTreasury", type: "address" },
          { name: "expiry", type: "uint256" },
          { name: "buyer", type: "address" },
          { name: "cidHash", type: "bytes32" },
        ],
      },
      { name: "signature", type: "bytes" },
      { name: "cid", type: "string" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "ownerOf",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tokenURI",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "Transfer",
    inputs: [
      { name: "from", type: "address", indexed: true },
      { name: "to", type: "address", indexed: true },
      { name: "tokenId", type: "uint256", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlateMinted",
    inputs: [
      { name: "tokenId", type: "uint256", indexed: true },
      { name: "buyer", type: "address", indexed: true },
      { name: "designId", type: "string", indexed: false },
    ],
    anonymous: false,
  },
] as const satisfies Abi;
TS

echo "Wrote contract address to $CONTRACT_TS"
echo "Done."
