#!/usr/bin/env tsx
/**
 * Reads src/lib/catalog/seed.ts and emits migrations/0002_seed.sql.
 * Run: pnpm tsx scripts/seed-export.ts
 */
import { writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

// Dynamic import to allow tsx to resolve TS path aliases
const { ARTISTS, DESIGNS } = await import(resolve(root, "src/lib/catalog/seed.ts"));

function esc(v: string | null | undefined): string {
  if (v == null) return "NULL";
  return "'" + String(v).replace(/'/g, "''") + "'";
}

function num(v: number | null | undefined): string {
  if (v == null) return "NULL";
  return String(v);
}

const lines: string[] = [
  "-- Auto-generated by scripts/seed-export.ts — do not edit manually.",
  "-- Re-run `pnpm tsx scripts/seed-export.ts` to regenerate.",
  "BEGIN;",
  "",
];

for (const a of ARTISTS) {
  lines.push(
    `INSERT OR IGNORE INTO artists (id, name, handle, city, style, years, booked, rate, bio, pieces, rating, seed, email) VALUES (` +
      [
        esc(a.id),
        esc(a.name),
        esc(a.handle),
        esc(a.city),
        esc(a.style),
        num(a.years),
        esc(a.booked),
        num(a.rate),
        esc(a.bio),
        num(a.pieces),
        esc(a.rating),
        num(a.seed),
        esc(a.email ?? null),
      ].join(", ") +
      `);`
  );
}

lines.push("");

for (const d of DESIGNS) {
  lines.push(
    `INSERT OR IGNORE INTO designs (id, n, title, artist_id, style, price, price_usd, status, placement, seed, token, minted, medium, sessions, drawn, token_id) VALUES (` +
      [
        esc(d.id),
        esc(d.n),
        esc(d.title),
        esc(d.artistId),
        esc(d.style),
        num(d.price),
        num(d.priceUsd),
        esc(d.status),
        esc(d.placement),
        num(d.seed),
        esc(d.token),
        esc(d.minted),
        esc(d.medium),
        num(d.sessions),
        num(d.drawn),
        num(d.token_id),
      ].join(", ") +
      `);`
  );
}

lines.push("");
lines.push("INSERT OR IGNORE INTO _migrations VALUES (2, strftime('%s','now'));");
lines.push("");
lines.push("COMMIT;");
lines.push("");

const outPath = resolve(root, "migrations/0002_seed.sql");
writeFileSync(outPath, lines.join("\n"), "utf8");
console.log(`Written: ${outPath}`);
