#!/usr/bin/env tsx
/**
 * Pins 15 ERC-721 metadata JSON files to NFT.Storage and writes
 * migrations/0003_cids.sql with UPDATE statements.
 * Also writes r2-uploads/metadata/<tokenId>.json for R2 fallback.
 *
 * IMPORTANT: Requires NFT_STORAGE_KEY env var set to your nft.storage API key.
 * Run pre-deploy: pnpm pin:metadata
 *
 * If NFT_STORAGE_KEY is absent, a STUB migrations/0003_cids.sql is written
 * with placeholder CIDs (bafyTODO<n>) so the rest of the build can proceed.
 * Replace with real CIDs by re-running this script with NFT_STORAGE_KEY set.
 */
import { writeFileSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

const { ARTISTS, DESIGNS } = await import(resolve(root, "src/lib/catalog/seed.ts"));

const NFT_STORAGE_KEY = process.env.NFT_STORAGE_KEY ?? "";
const R2_PUBLIC_URL = process.env.R2_PUBLIC_URL ?? "https://pub-placeholder.r2.dev";
const IS_STUB = !NFT_STORAGE_KEY;

if (IS_STUB) {
  console.warn(
    "[pin-metadata] NFT_STORAGE_KEY not set — writing STUB migrations/0003_cids.sql with placeholder CIDs.\n" +
      "  Re-run with NFT_STORAGE_KEY set before wrangler d1 execute 0003_cids.sql."
  );
}

interface Erc721Metadata {
  name: string;
  description: string;
  image: string;
  external_url: string;
  attributes: Array<{ trait_type: string; value: string | number }>;
}

function buildMetadata(design: (typeof DESIGNS)[0]): Erc721Metadata {
  const artist = ARTISTS.find((a: { id: string }) => a.id === design.artistId)!;
  return {
    name: `SUKNID — ${design.title}`,
    description: `${design.title} by ${artist.name}. ${artist.bio}`,
    image: `${R2_PUBLIC_URL}/metadata/${design.token_id}.json`,
    external_url: `https://suknid.pages.dev/design/${design.id}`,
    attributes: [
      { trait_type: "Artist", value: artist.name },
      { trait_type: "Style", value: design.style },
      { trait_type: "Placement", value: design.placement },
      { trait_type: "Medium", value: design.medium },
      { trait_type: "Sessions", value: design.sessions },
      { trait_type: "Edition", value: design.n },
      { trait_type: "Price (ETH)", value: design.price },
      { trait_type: "City", value: artist.city },
    ],
  };
}

async function pinWithRetry(
  metadata: Erc721Metadata,
  tokenId: number,
  retries = 3
): Promise<string> {
  // Dynamic import so the module only loads when key is available
  const { NFTStorage, File } = await import("nft.storage");
  const client = new NFTStorage({ token: NFT_STORAGE_KEY });

  let lastErr: unknown;
  for (let attempt = 0; attempt < retries; attempt++) {
    try {
      const blob = new File(
        [JSON.stringify(metadata, null, 2)],
        `${tokenId}.json`,
        { type: "application/json" }
      );
      const cid = await client.storeBlob(blob);
      return cid;
    } catch (err) {
      lastErr = err;
      const wait = Math.pow(2, attempt) * 1000;
      console.warn(`[pin-metadata] token ${tokenId} attempt ${attempt + 1} failed, retrying in ${wait}ms`);
      await new Promise((r) => setTimeout(r, wait));
    }
  }
  throw new Error(`[pin-metadata] Failed to pin token ${tokenId} after ${retries} attempts: ${lastErr}`);
}

const r2Dir = resolve(root, "r2-uploads/metadata");
mkdirSync(r2Dir, { recursive: true });

const updates: string[] = [];

for (const design of DESIGNS) {
  const meta = buildMetadata(design);
  const r2Path = resolve(r2Dir, `${design.token_id}.json`);
  writeFileSync(r2Path, JSON.stringify(meta, null, 2), "utf8");

  let cid: string;
  if (IS_STUB) {
    cid = `bafyTODO${design.token_id}`;
  } else {
    console.log(`[pin-metadata] Pinning token ${design.token_id} (${design.title})...`);
    cid = await pinWithRetry(meta, design.token_id);
    console.log(`[pin-metadata] token ${design.token_id} => ${cid}`);
  }

  updates.push(`UPDATE designs SET ipfs_cid='${cid}' WHERE id='${design.id}';`);
}

const sqlLines = [
  "-- Auto-generated by scripts/pin-metadata.ts — do not commit (see .gitignore).",
  IS_STUB
    ? "-- STUB: real CIDs not set. Re-run with NFT_STORAGE_KEY before applying this migration."
    : "-- Real CIDs pinned to NFT.Storage.",
  "BEGIN;",
  "",
  ...updates,
  "",
  "INSERT OR IGNORE INTO _migrations VALUES (3, strftime('%s','now'));",
  "",
  "COMMIT;",
  "",
];

const outPath = resolve(root, "migrations/0003_cids.sql");
writeFileSync(outPath, sqlLines.join("\n"), "utf8");
console.log(`Written: ${outPath}${IS_STUB ? " (STUB — replace before deploy)" : ""}`);
